// flow-typed signature: f7e0fba0f5af012b035102fdb5b96824
// flow-typed version: <<STUB>>/talkiejs_v^0.11.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'talkiejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'talkiejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'talkiejs/dist/talkie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'talkiejs/dist/talkie.min.js' {
  declare module.exports: $Exports<'talkiejs/dist/talkie.min'>;
}
