// flow-typed signature: 2f69d898ba9c8b6b0179a9f0355335a6
// flow-typed version: <<STUB>>/@webpack-blocks/extract-text_v^0.4.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webpack-blocks/extract-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@webpack-blocks/extract-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webpack-blocks/extract-text/index' {
  declare module.exports: $Exports<'@webpack-blocks/extract-text'>;
}
declare module '@webpack-blocks/extract-text/index.js' {
  declare module.exports: $Exports<'@webpack-blocks/extract-text'>;
}
