// flow-typed signature: bc5d1d6b031d375ce79ae59e1c95b6f5
// flow-typed version: <<STUB>>/@webpack-blocks/webpack_v^0.4.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webpack-blocks/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@webpack-blocks/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/app' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/webpack.config' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/minimal/app' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/minimal/webpack.config' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/app' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/webpack.config' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__e2e-fixtures__/typescript/webpack.config' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__tests__/end-to-end.test' {
  declare module.exports: any;
}

declare module '@webpack-blocks/webpack/__tests__/integration.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/app.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/app'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/webpack.config.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/babel-postcss-extract-text/webpack.config'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/minimal/app.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/minimal/app'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/minimal/webpack.config.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/minimal/webpack.config'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/app.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/app'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/webpack.config.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/sass-extract-text/webpack.config'>;
}
declare module '@webpack-blocks/webpack/__e2e-fixtures__/typescript/webpack.config.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__e2e-fixtures__/typescript/webpack.config'>;
}
declare module '@webpack-blocks/webpack/__tests__/end-to-end.test.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__tests__/end-to-end.test'>;
}
declare module '@webpack-blocks/webpack/__tests__/integration.test.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack/__tests__/integration.test'>;
}
declare module '@webpack-blocks/webpack/index' {
  declare module.exports: $Exports<'@webpack-blocks/webpack'>;
}
declare module '@webpack-blocks/webpack/index.js' {
  declare module.exports: $Exports<'@webpack-blocks/webpack'>;
}
